### ISSUE TITLE
Bom Submission

### ISSUE THREAD

**Issue by timChase98** [CPasteris1/ECE-388-Design-Project-Cameron-Pasteris#1]
- [x] Price breakdowns should be unit price not extended price 
- [x] Add me as an owner to the repo

Please check off the issues as you fix them. When you are done push your changes, create a new release, and close the issue with a comment that @s me. I'll review your changes and mark you as good to order parts or I'll open a new issue if you need to make changes.

**Comment by CPasteris1** [comment]
@timChase98 I fixed the pricing, and added you as a collaborator

**Comment by timChase98** [comment]
Looks good!
