### ISSUE TITLE
Schematic Submission

### ISSUE THREAD

**Issue by timChase98** [CPasteris1/ECE-388-Design-Project-Cameron-Pasteris#2]
- [x] Add me as an admin to the repo
- [x] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [x] All project files should be version controlled
- [x] Schematics should have clear flow from left-right 
  - [x] Power input top left
  - [x] Inputs to uController middle left 
  - [x] uController in the center
  - [x] uController outputs to right  
- [x] Why is aref connected to gnd? 
- [x] Power flags should be used over named nets for power distribution 
- [x] The chip select pin for all SPI parts should have an external pull up resistor

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by CPasteris1** [comment]
I believe I have fixed these problems now, I'll make a new release for the schematic, still working on my next board layout

**Comment by timChase98** [comment]
To get accepted 
- [x] What is the purpose of R11? 
- [x] Change the value of R7 to 10k
- [x] Add test points.  Power and GND are required others are up to you
- [x] VOUT on U5 has no connection.    
- [x] C14 and C15 are drawn as polarized capacitors in reverse bias
  - [x] If you did not intend to use a polarized cap change to a non polarized symbol
  - [x] If you did intend to use a polarized cap fix polarity 
- [x] Change VCC flag to match the voltage carried by the flag.  ex 5V -12V 3.3V 
- [x] Change 3.3_VCC to a 3.3V power flag


To get a PASS
- [x] Net labels should sit on top of the net 
- [x] Label sub sections of your circuit to make logical connections clear

**Comment by CPasteris1** [comment]
These should all be fixed now. I updated the release for the schematic.

**Comment by timChase98** [comment]
Looks good I'll give this a pass.  You can move onto layout
