### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by timChase98** [CPasteris1/ECE-388-Design-Project-Cameron-Pasteris#3]
- [x] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [x] All project files should be version controlled
- [x] Boards will not be graded unless both Eagle files and correctly generated Gerber files are present
- [x] All traces should hit the center of pads
- [x] Power traces should have a minimum width of 12 mil or run through a plane
- [x] Silkscreen labels must include
  - [x] Your Name
  - [x] Project Name
  - [x] Date
  - [x] Version/Rev
  - [x] Github Link
- [x] Check stock sheet for correct footprints for 
  - [x] USB connector
  - [x] Pots
  - [x] Diodes
  - [x] Caps
  - [x] Buttons 
  - [x] OLED
- [x] Your project would fit on a much smaller board
- [x] Placement of fiducials should be 
  - [x] FID1 lower left 
  - [x] FID2 upper left
  - [x] FID3 lower right
- [x] Silkscreen cant overlap outside of board 
 
These are initial comments meant to guide you through the layout process.  I will not look at your board again until your schematic passes review.  This is to reduce the workload on you by limiting the number of times you need to relayout your board due to schematic errors.  

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by CPasteris1** [comment]
I updated as many footprints as I could, most of them I made by following the datasheets' layouts. The OLED I did not update, because there was no datasheet for the display on the website, and from the information I could find it has the same dimensions as the footprint that is on my board. It is not a smaller board, I tried to condense it, but I also had to fit the silkscreen info.

**Comment by timChase98** [comment]
You have silkscreen off the edge of your board.  Fix this and I'll accept your layout.

**Comment by CPasteris1** [comment]
Should be all set now, I think I moved all labels and silkscreen to make sure it wasn't over the edge.

**Comment by timChase98** [comment]
I'll accept this.

**Comment by timChase98** [comment]
Your board was sent to fab
